version: '3'
services:
  producer:
    build: ./producer
    image: producer
    networks:
      - kafka
    volumes:
      - ./producer/producer.py:/root/producer.py
  kafka:
    image: mario2904/kafka
    hostname: kafka
    networks:
      - kafka
  consumer:
    build: ./consumer
    image: consumer
    networks:
      - hadoop
      - kafka
    volumes:
      - ./consumer/consumer.py:/root/consumer.py
  master:
    image: mario2904/hadoop
    command: ["sh", "-c", "init-hadoop-master.sh; tail -f /dev/null"]
    hostname: master
    networks:
      - hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
  slave:
    image: mario2904/hadoop
    command: ["sh", "-c", "init-hadoop-slave.sh; tail -f /dev/null"]
    networks:
      - hadoop
networks:
  hadoop:
  kafka:
